AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class CheckingAccountController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccount = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First();
            return View(checkingAccount);
        }

        [Authorize(Roles="Admin")]
        public ActionResult DetailsForAdmin(int Id)
        {
            var userId = User.Identity.GetUserId();
            var checkingAccount = db.CheckingAccounts.Find(Id);
            return View("Details", checkingAccount);
        }

        [Authorize(Roles="Admin")]
        public ActionResult List() {
            return View(db.CheckingAccounts.ToList());
        }

        public ActionResult Statement(int id) {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View(checkingAccount.Transactions.ToList());
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomatedTellerMachine/Controllers/HomeController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{

    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c=>c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            // ViewBag'i külge saab suvalisi atribuute panna
            ViewBag.TheMessage = "Kui sul on probleeme, saada meile teade.";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            ViewBag.TheMessage = "Aitäh, saime sinu teate kätte!";

            return PartialView("_ContactThanks"); // Alljoon nime ees on konventsioon
        }

        // GET: /Home/Test saadab ära /Home/About lehele
        // View ilma nimeta saadab meetodi nimega View, nimega otsib vastava View
        public ActionResult Test() {
            return View("About");
        }

        public ActionResult Serial(string letterCase) {
            var serial = "ASPNETMVC5ATM1";
            if (letterCase == "lower") {
                return Content(serial.ToLower());
            }
            return Content(serial);
        }
    }
}

AutomatedTellerMachine/Controllers/TransactionController.cs
using AutomatedTellerMachine.Models;
using AutomatedTellerMachine.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        // Kasutame liidest selleks, et oleks võimalik
        // andmebaasiobjekti testides mock'ida
        private IApplicationDbContext db;

        public TransactionController() {
            db = new ApplicationDbContext();
        }

        public TransactionController(IApplicationDbContext dbContext) {
            db = new ApplicationDbContext();
        }

        // GET: Transaction/Deposit
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }

        // POST: Transaction/Deposit
        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            // Kui sisestati negatiivne summa
            if (transaction.Amount < 0)
            {
                ModelState.AddModelError("Amount", "Sisestatud summa peab olema positiivne!");
            }

            if (ModelState.IsValid)
            {
                // Uus raha lisamine
                db.Transactions.Add(transaction);
                db.SaveChanges();
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: Transaction/Withdraw
        public ActionResult Withdraw(int checkingAccountId)
        {
            return View();
        }

        // POST: Transaction/Withdraw
        [HttpPost]
        public ActionResult Withdraw(Transaction transaction)
        {
            // Võtan konto, et kontrollida, kas on piisavalt vahendeid.
            var checkingAccount = db.CheckingAccounts.Find(transaction.CheckingAccountId);

            if (transaction.Amount > checkingAccount.Balance) {
                ModelState.AddModelError("Amount", "Kontol ei ole piisavalt vahendeid!");
            }

            if (ModelState.IsValid)
            {
                // Muudan summa negatiivseks, et lisamise asemel maha lahutada
                transaction.Amount = -transaction.Amount;

                // Uus raha lisamine
                db.Transactions.Add(transaction);
                db.SaveChanges();
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "Meist";
}

<h2>Meist</h2>

<p>Oleme esimene veebipõhine pangaautomaat!</p>

AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}
<h2>Saada meile teade</h2>

<div id="formSection">
    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "formSection" })) {
        <textarea name="message"></textarea>
        <input type="submit" value="Send" />
    }
</div>

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Pealeht";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Withdraw", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-arrow-down"></span> Raha välja</a>
        <a href="#" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-flash"></span> Kiire 5€</a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-question-sign"></span> Kontojääk</a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Statement", "CheckingAccount", new { id=ViewBag.CheckingAccountId })" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-print"></span> Konto väljavõte</a>
        <a href="#" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-transfer"></span> Ülekanne</a>
        <a href="@Url.Action("Deposit", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-circle-arrow-up"></span> Raha sisse</a>
    </div>
</div>

AutomatedTellerMachine/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.TheMessage</h3>